title:                  "Hans Bonini"
email:                  "hans@ysolutions.com.br"
baseurl:                ""
url:                    "https://hansbonini.com.br"
exclude:                ['package.json', 'src', 'node_modules']
collections:
    posts:
        output:         true
        permalink:       "/api/post/:title"
    categories:
        output:         true
        permalink:       "/api/category/:title"
