title:                  "Hans Bonini"
email:                  "hans@ysolutions.com.br"
baseurl:                ""
url:                    "https://hansbonini.com.br"
exclude:                ['package.json', 'src', 'node_modules']
include:                ['.htaccess']
plugins:
    - jekyll-assets
collections:
    posts:
        output:         true
        permalink:       "/api/post/:title"
    categories:
        output:         true
        permalink:       "/api/category/:title"
assets:
    compress:
        css: false
        js: false
        skip_baseurl_with_cdn: false
        skip_prefix_with_cdn: false
        prefix: "/assets"
    assets:
        - "*.js"
        - "*.css"
        - "*.woff"
